### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by SuselMan** [nuxt-modules/web-vitals#63]
I connected web-vitals to nuxt3 app using  `buildModules: [
    '@nuxtjs/web-vitals',
  ],
  webVitals: {
    provider: 'log',
    debug: true,
  },`

But i cannot see anything related to this in console? Also I tried a custom API config but there were nothing in network tab as well. How should it work? BTW I use nuxt3 + vue3 in the project

**Comment by danielroe** [comment]
Nuxt 3 does not use `buildModules` but modules. Updating the docs now: https://github.com/nuxt-modules/web-vitals/commit/06fe0309c065c28fa9dce7d253336a263d0139f9
