### ISSUE TITLE
Events execute twice

### ISSUE THREAD

**Issue by burda-osowiecki** [nuxt-modules/web-vitals#65]
![image](https://user-images.githubusercontent.com/118734217/236500423-90ca1c27-60ca-47b0-b7d6-05c7420f7542.png)
![image](https://user-images.githubusercontent.com/118734217/236500438-a4e5f79c-a140-481e-b5dd-68f76ebff064.png)

**Comment by burda-osowiecki** [comment]
@danielroe

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt-modules/web-vitals/pull/66
